### ISSUE TITLE
Readme.md should show Configuration 4: Inverting PGA inputs with PD3, PD7 & PE3

### ISSUE THREAD

**Issue by hinzvc** [microchip-pic-avr-examples/avr128db48-cnano-opamp-demo-fw-studio#1]
Configuration 4: Inverting PGA shows the RESMUXBOT (Vin) as INP but are INN (negative input)

**Comment by egilro** [comment]
Thank you for pointing this out @hinzvc, it should be fixed now. Sorry for the slow feedback.
